version: '2'

services:
  ca:
    container_name: ca
    image: hyperledger/fabric-ca:1.4
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca
    command: sh -c 'fabric-ca-server start -b bootstrap:bootstrappw'
    volumes:
      - ./ca:/etc/hyperledger/fabric-ca-server
      - ./ca-clients:/root/ca-clients
    ports:
      - 7054:7054

  orderer:
    container_name: orderer
    image: hyperledger/fabric-orderer:1.4
    environment:
      - FABRIC_LOGGING_SPEC=debug
      - ORDERER_GENERAL_LISTENADDRESS=orderer
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/msp
      - GRPC_TRACE=all=true,
      - GRPC_VERBOSITY=debug
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
      - ./ca-clients/orderer/msp:/etc/hyperledger/msp
      - ./genesis.block:/etc/hyperledger/fabric/genesis.block
    ports:
      - 7050:7050

  peer0.zhigui.com:
    container_name: peer0.zhigui.com
    image: hyperledger/fabric-peer:1.4
    environment:
      - CORE_PEER_ID=peer0.zhigui.com
      - CORE_PEER_ADDRESS=peer0.zhigui.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.zhigui.com:7051
      - CORE_PEER_LOCALMSPID=ZhiguiMSP
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp
      # CouchDB Configuration
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_TOTALQUERYLIMIT=100000
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_INTERNALQUERYLIMIT=1000
    volumes:
        - /var/run/:/host/var/run/
        - ./ca-clients/zhigui.com/peers/peer0.zhigui.com/msp:/etc/hyperledger/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start --peer-chaincodedev=true
    ports:
      - 7051:7051
      - 7053:7053
    depends_on:
      - couchdb0

  couchdb0:
    container_name: couchdb0
    image: hyperledger/fabric-couchdb:0.4.18
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - 5984:5984

  peer1.zhigui.com:
    container_name: peer1.zhigui.com
    image: hyperledger/fabric-peer:1.4
    environment:
      - CORE_PEER_ID=peer1.zhigui.com
      - CORE_PEER_ADDRESS=peer1.zhigui.com:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.zhigui.com:8051
      - CORE_PEER_LOCALMSPID=ZhiguiMSP
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp
      # CouchDB Configuration
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_TOTALQUERYLIMIT=100000
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_INTERNALQUERYLIMIT=1000
    volumes:
        - /var/run/:/host/var/run/
        - ./ca-clients/zhigui.com/peers/peer1.zhigui.com/msp:/etc/hyperledger/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start --peer-chaincodedev=true
    ports:
      - 8051:8051
      - 8053:8053
    depends_on:
      - couchdb1

  couchdb1:
    container_name: couchdb1
    image: hyperledger/fabric-couchdb:0.4.18
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - 6984:5984

  peer0.ibm.com:
    container_name: peer0.ibm.com
    image: hyperledger/fabric-peer:1.4
    environment:
      - CORE_PEER_ID=peer0.ibm.com
      - CORE_PEER_ADDRESS=peer0.ibm.com:9051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.ibm.com:9051
      - CORE_PEER_LOCALMSPID=IBMMSP
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp
      # CouchDB Configuration
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_TOTALQUERYLIMIT=100000
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb2:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_INTERNALQUERYLIMIT=1000
    volumes:
        - /var/run/:/host/var/run/
        - ./ca-clients/ibm.com/peers/peer0.ibm.com/msp:/etc/hyperledger/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start --peer-chaincodedev=true
    ports:
      - 9051:9051
      - 9053:9053
    depends_on:
      - couchdb2

  couchdb2:
    container_name: couchdb2
    image: hyperledger/fabric-couchdb:0.4.18
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - 7984:5984

  peer1.ibm.com:
    container_name: peer1.ibm.com
    image: hyperledger/fabric-peer:1.4
    environment:
      - CORE_PEER_ID=peer1.ibm.com
      - CORE_PEER_ADDRESS=peer1.ibm.com:10051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.ibm.com:10051
      - CORE_PEER_LOCALMSPID=IBMMSP
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp
      # CouchDB Configuration
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_TOTALQUERYLIMIT=100000
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb3:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_INTERNALQUERYLIMIT=1000
    volumes:
        - /var/run/:/host/var/run/
        - ./ca-clients/ibm.com/peers/peer1.ibm.com/msp:/etc/hyperledger/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start --peer-chaincodedev=true
    ports:
      - 10051:10051
      - 10053:10053
    depends_on:
      - couchdb3

  couchdb3:
    container_name: couchdb3
    image: hyperledger/fabric-couchdb:0.4.18
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - 8984:5984

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:1.4
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.zhigui.com:7051
      - CORE_PEER_LOCALMSPID=ZhiguiMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/ca-clients/zhigui.com/peers/peer0.zhigui.com/msp
    working_dir: /opt/gopath/src/chaincodedev
    command: /bin/bash -c './script.sh'
    volumes:
        - /var/run/:/host/var/run/
        - ./ca-clients:/etc/hyperledger/ca-clients
        # - ./chaincode:/opt/gopath/src/chaincodedev/chaincode
        - ./:/opt/gopath/src/chaincodedev/

  chaincode:
    container_name: chaincode
    image: hyperledger/fabric-ccenv:1.4
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_ID=example02
      - CORE_PEER_ADDRESS=peer0.zhigui.com:7051
      - CORE_PEER_LOCALMSPID=ZhiguiMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/ca-clients/zhigui.com/peers/peer0.zhigui.com/msp
    working_dir: /opt/gopath/src/chaincode
    command: /bin/bash -c 'sleep 6000000'
    volumes:
        - /var/run/:/host/var/run/
        - ./ca-clients:/etc/hyperledger/ca-clients
        - ./chaincode:/opt/gopath/src/chaincode
